### ISSUE TITLE
api網址問題

### ISSUE THREAD

**Issue by tks3589** [pokobunhsu/langTool#1]
您好，請問是如何獲取這些服務post的api網址，因為之前浪有開播訊息的api，( https://tw.api.langlive.com/v2/activity/Flyer/AKB48TP )，
但之後關掉了，想請問有沒有辦法能重新得到api，謝謝。

**Comment by pokobunhsu** [comment]
哈囉，這個api是從浪裡面抓出來的喔~
至於說開播訊息的API可能因為流量暴增導致整個api變成失效狀態，但app裡面能不能找到我就不太清楚了，如果需要你可以去抓看看他送出的封包有無包含開播訊息的API~也謝謝你的星星囉:D

**Comment by tks3589** [comment]
請問是利用類似mitmproxy的工具抓取的嗎

**Comment by pokobunhsu** [comment]
對的，如果是android可以推薦使用packet capture去抓取喔！

**Comment by tks3589** [comment]
了解，感謝回覆~
